[target.armv7-linux-androideabi]
linker = "arm-linux-androideabi-clang"
ar = "arm-linux-androideabi-ar"

[target.i686-linux-android]
linker = "i686-linux-android-clang"
ar = "i686-linux-android-ar"

[target.x86_64-linux-android]
linker = "x86_64-linux-android-clang"
ar = "x86_64-linux-android-ar"

[target.aarch64-linux-android]
linker = "aarch64-linux-android-clang"
ar = "aarch64-linux-android-ar"